name: HTML to PDF Workflow

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: HTML-PDF

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step to build the static site or create the public directory
    - name: Build static site (or create public folder)
      run: |
        # Example: npm run build if you're using a Node.js build tool like Next.js
        # Or another command to generate files in the public folder
        mkdir -p ./public
        echo "<html><body>Test PDF</body></html>" > ./public/index.html

    # Step to list the files to verify the public directory
    - name: Check public directory
      run: |
        if [ -d "./public" ]; then
          echo "public directory exists."
          ls -al ./public
        else
          echo "public directory does not exist."
          exit 1
        fi

    # Step to convert HTML to PDF
    - name: Convert HTML to PDF
      uses: fifsky/html-to-pdf-action@master
      with:
        htmlFile: ./public/index.html
        outputFile: ./public/resume.pdf
        pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

    # Step to check if resume.pdf was created
    - name: Check if resume.pdf was created
      run: |
        if [ -f "./public/resume.pdf" ]; then
          echo "PDF was created successfully."
          ls -al ./public/resume.pdf
        else
          echo "Failed to create resume.pdf."
          exit 1
        fi
